In [25]:
import pandas as pd 
import numpy as np 
from sklearn.utils import shuffle

df = pd.DataFrame()
colnames=['Review','Sentiment'] 
df = pd.read_csv('Stemmedlines_reviews.csv',encoding='utf-8',names=colnames)
df.set_index(['Review', 'Sentiment'])

df[df==np.inf]=np.nan
df.fillna(0, inplace=True)
df = shuffle(df).reset_index(drop=True)

X_train=df.loc[:250,'Review'].values
X_test=df.loc[251:,'Review'].values
Y_train=df.loc[:250,'Sentiment'].values
Y_test=df.loc[251:,'Sentiment'].values
df.head(10)

Review  Sentiment
0  సుమంత్ అశ్విన్ ‌ - పూజ జ ‌ వేరి జంట ‌ గా కాలం ...          0
1  భూపతి రాజ - శివం మాట శ్రీనివాస్ రెడ్డి స్క్రీన...          1
2  మయూరినయనతార ఓ జూనియర్ ఆర్టిస్ట్ సినిమా ఇష్టపడు...          1
3  కృష్ణ ప్రభుదేవా ఓ మారుమూల పల్లెటూరు నుంచి ముంబ...          1
4  జానకి ( దీక్ష పంత్ ) ఓ హీరోయిన్ ఆమె నటించు ‘ బ...          0
5  గౌతమ్ ( రాజ్ తరుణ్ ) పుట్టుక అంధ అతను ఓ ఆశ్రమం...          0
6  గత కొంతకాలం వరుస పరాజయాలతో సతమతమవుతున్న కోన వె...          0
7  జార్ఖండ్ రాజధాని రాంచిలో ఓ దిగువ మధ్య తరగతి కు...          1
8  ఆత్రేయపురం అనే గ్రామం అల్లరి చిల్లరిగా తిరిగేస...          1
9  ఆదిత్య నాను దర్శకుడు రాజమౌళి దగ్గర సహాయం దర్శక...          1

In [26]:
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences

tokenizer_obj = Tokenizer()
Total_Reviews = df.loc[:,'Review'].values
tokenizer_obj.fit_on_texts(Total_Reviews)

#pad sequence
max_length= max([len(s.split()) for s in Total_Reviews])

#size of the vocabulary
vocabulary_size = len(tokenizer_obj.word_index) +1 

X_train_tokens = tokenizer_obj.texts_to_sequences(X_train)
X_test_tokens = tokenizer_obj.texts_to_sequences(X_test)

X_train_pad = pad_sequences (X_train_tokens,maxlen=max_length,padding="post")
X_train_pad = np.nan_to_num(X_train_pad)

X_test_pad = pad_sequences (X_test_tokens,maxlen=max_length,padding="post")
X_test_pad = np.nan_to_num(X_test_pad)

Total_Reviews_tokens = tokenizer_obj.texts_to_sequences(X_train)
Total_reviews_pad = pad_sequences(Total_Reviews_tokens,maxlen=max_length,padding="post")

print(X_train_pad,X_test_pad)

[[ 760  861    7 ...    0    0    0]
 [1574  320  643 ...    0    0    0]
 [7932   22 4336 ...    0    0    0]
 ...
 [3226 1760 1276 ...    0    0    0]
 [ 887  422   43 ...    0    0    0]
 [ 188 3695  422 ...    0    0    0]] [[2489  968  493 ...    0    0    0]
 [1231  109  139 ...    0    0    0]
 [2698 1996 4308 ...    0    0    0]
 ...
 [  27  989 1410 ...    0    0    0]
 [1882  882  558 ...    0    0    0]
 [2442 1828  399 ...    0    0    0]]


In [27]:
# Import svmmodel
from sklearn import svm
from sklearn.model_selection import train_test_split

print(len(Total_reviews_pad))
print(len(df.loc[:,'Sentiment'].values))
X_train, X_test, y_train, y_test = train_test_split(Total_reviews_pad,df.loc[:,'Sentiment'].values, test_size=0.2, random_state=42)
#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


ValueError: Found input variables with inconsistent numbers of samples: [251, 268]