In [50]:
import pandas as pd 
import numpy as np 
from sklearn.utils import shuffle

df = pd.DataFrame()
colnames=['Review','Sentiment'] 
df = pd.read_csv('combined_reviews.csv',encoding='utf-8',names=colnames)
df.set_index(['Review', 'Sentiment'])
df = shuffle(df).reset_index(drop=True)

X_train=df.loc[:550,'Review'].values
X_test=df.loc[551:,'Review'].values
Y_train=df.loc[:550,'Sentiment'].values
Y_test=df.loc[551:,'Sentiment'].values
df.head(10)

Review  Sentiment
0  ఈ పుస్తకం అందరు సిఫార్సు చెయ్యి ఈ పుస్తకం తొంద...          1
1  ఇది Mr భగత్ యెుకక మరొక చైల్డిష్ పుస్తకం అతను ...          0
2  సంజీవ్ రెడ్డి మాట నివాస్ స్క్రీన్ప్లే దర్శకత్వ...          1
3  సౌండ్ నాణ్యత బాగోలేదు సాధారణం స్పీకర్ వీడియో న...          0
4  విజయేంద్ర ప్రసాద్ నిర్మాత అనిత కుమారస్వామి స్క...          0
5  క్రోమా మార్కెట్ లోని రిలయన్స్ డిజిటల్ ఎక్స్ప్ర...          1
6  కథః నరేష్ ( అల్లరి నరేష్ ) పెళ్లి బ్యాండ్ మేళం...          0
7  జియోమి రెడ్మి 4 A మొబైల్ చాలా అద్భుతం ఉండు ఇద...          1
8  అవ్వు ప్రేమ రెండుసార్లు కలుగు మీరు మొదట ప్రేమ ...          1
9  దాని ఫీచర్ చూడు నేను ఈ ఫోన్ను అధికారికం సైట్ న...          0

In [51]:
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences

tokenizer_obj = Tokenizer()
Total_Reviews = df.loc[:,'Review'].values
tokenizer_obj.fit_on_texts(Total_Reviews)

#pad sequence
max_length= max([len(s.split()) for s in Total_Reviews])

#size of the vocabulary
vocabulary_size = len(tokenizer_obj.word_index) +1 
X_train_tokens = tokenizer_obj.texts_to_sequences(X_train)
X_test_tokens = tokenizer_obj.texts_to_sequences(X_test)

X_train_pad = pad_sequences (X_train_tokens,maxlen=max_length,padding="post")
X_test_pad = pad_sequences (X_test_tokens,maxlen=max_length,padding="post")

Total_Reviews_tokens = tokenizer_obj.texts_to_sequences(X_train)
Total_reviews_pad = pad_sequences(Total_Reviews_tokens,maxlen=max_length,padding="post")

print(X_train_pad)
print(max_length)

[[    4    42   187 ...     0     0     0]
 [   28  2887  1410 ...     0     0     0]
 [ 6200   343   115 ...     0     0     0]
 ...
 [  246  1293 20612 ...     0     0     0]
 [ 1764   766     1 ...     0     0     0]
 [  124   769   446 ...     0     0     0]]
1670


In [52]:
import numpy as np

f1=open("Sentiment_1.txt")
lines=f1.readlines()
vocabulary_words = []
vectors=[]
vocabulary = { x:i  for x,i in enumerate(vocabulary_words)}
for line in lines :
    line = line[:-1]
    line = line.split(' ')
    vocabulary_words.append(line[0])
    
    vectors.append(line[1:len(line)-1])
    # print(len(line))



Embedding_size =100
vocabulary = { x:i  for x,i in enumerate(vocabulary_words)}
print(vocabulary)
print(len(vocabulary))
print(vectors[0])
embeddings = 1 * np.random.randn(len(vocabulary_words) + 1,100)
embeddings[0] = 0 

for index,word in vocabulary.items():
    embeddings[index] = vectors[index]

print(embeddings.shape)
print(embeddings)

{0: 'సినిమా', 1: 'చెయ్యి', 2: 'ఉండు', 3: 'ఈ', 4: '’', 5: '‘', 6: 'కూడా', 7: '\u200c', 8: 'తాను', 9: 'కథ', 10: 'పాత్ర', 11: 'ఆ', 12: 'కానీ', 13: 'చాలా', 14: 'హీరో', 15: 'నేను', 16: 'చూడు', 17: 'సన్నివేశం', 18: 'వచ్చు', 19: 'గా', 20: 'లో', 21: 'అనిపించు', 22: 'ప్రేక్షకుడు', 23: 'చెప్పు', 24: 'అతడు', 25: 'ఓ', 26: '-', 27: 'మరియు', 28: 'ఇది', 29: 'ఒక', 30: 'కనిపించు', 31: 'ఐతే', 32: 'లేదు', 33: 'ఆమె', 34: 'విషయం', 35: 'దర్శకుడు', 36: '.', 37: 'మంచి', 38: 'కామెడీ', 39: 'సాగు', 40: 'కథనం', 41: 'చూపించు', 42: 'అవ్వు', 43: 'పుస్తకం', 44: 'అతను', 45: 'బాగా', 46: 'మాత్రం', 47: 'చివర', 48: 'కొన్ని', 49: 'హీరోయిన్', 50: 'అది', 51: 'పెద్ద', 52: 'పడు', 53: 'పాట', 54: 'ను', 55: 'బాగుండు', 56: 'గురించి', 57: 'కోసం', 58: 'కు', 59: 'ఇవ్వు', 60: 'ఎలా', 61: 'ఆకట్టుకో', 62: 'తర్వాత', 63: 'మీద', 64: 'అని', 65: 'నుంచి', 66: 'కొంచెం', 67: ')', 68: '(', 69: 'మధ్య', 70: 'అనే', 71: 'నటన', 72: 'కెమెరా', 73: 'తో', 74: 'పెట్టు', 75: 'నటించు', 76: 'ప్రయత్నం', 77: 'బాగానే', 78: 'అమ్మాయి', 79: 'ప్రేమ', 80: 'అన్న', 81:

(23044, 100)
[[ 1.17857000e-01  5.72670000e-02  3.62550000e-02 ...  2.33940000e-02
   6.11000000e-03  1.21650000e-02]
 [ 1.17919000e-01  1.09870000e-01  6.19610000e-02 ...  4.60950000e-02
  -1.42900000e-02  8.05710000e-02]
 [ 9.77810000e-02  7.97160000e-02  3.76250000e-02 ...  9.18800000e-03
  -8.89790000e-02  1.36000000e-03]
 ...
 [ 1.11677000e-01  1.29377000e-01  1.10934000e-01 ...  2.30660000e-02
  -2.22710000e-02  1.51219000e-01]
 [ 4.85350000e-02 -3.98410000e-02  9.58790000e-02 ... -1.14110000e-01
  -4.47340000e-02  1.23940000e-01]
 [ 1.78082088e-01  3.72997802e-01  1.26641732e+00 ... -1.81870379e+00
  -3.74339796e-01 -1.28590815e+00]]


In [53]:
from keras.models import Sequential
from keras.layers import Dense,Embedding,LSTM,GRU
from keras.layers.embeddings import Embedding
from gensim.models import Word2Vec
from keras.regularizers import l2
from keras import optimizers

model=Sequential()
model.add(Embedding(len(embeddings), Embedding_size ,weights=[embeddings] ,input_length=max_length, trainable=True))
model.add(LSTM(units=75, dropout=0.2, recurrent_dropout=0.2, return_sequences=False))
model.add(Dense(64, activation='softmax'))
sgd = optimizers.SGD(lr=0.01, clipvalue=0.5)
model.compile(loss = 'sparse_categorical_crossentropy' , optimizer = sgd, metrics = ['accuracy'])



In [54]:
print("Training")

model.fit(X_train_pad,Y_train,epochs =10, batch_size =8, validation_data = (X_test_pad,Y_test),verbose=2)

Training
Train on 551 samples, validate on 121 samples
Epoch 1/10
 - 41s - loss: 3.2385 - accuracy: 0.4156 - val_loss: 1.8023 - val_accuracy: 0.4215
Epoch 2/10
 - 40s - loss: 1.1489 - accuracy: 0.5045 - val_loss: 0.8470 - val_accuracy: 0.4215
Epoch 3/10
 - 43s - loss: 0.7951 - accuracy: 0.5100 - val_loss: 0.7839 - val_accuracy: 0.4215
Epoch 4/10
 - 44s - loss: 0.7467 - accuracy: 0.5118 - val_loss: 0.7435 - val_accuracy: 0.4215
Epoch 5/10
 - 45s - loss: 0.7283 - accuracy: 0.5064 - val_loss: 0.7192 - val_accuracy: 0.4215
Epoch 6/10
 - 45s - loss: 0.7195 - accuracy: 0.4991 - val_loss: 0.7261 - val_accuracy: 0.4215
Epoch 7/10
 - 43s - loss: 0.7149 - accuracy: 0.5263 - val_loss: 0.7049 - val_accuracy: 0.5785
Epoch 8/10
 - 45s - loss: 0.7156 - accuracy: 0.4701 - val_loss: 0.7343 - val_accuracy: 0.4215
Epoch 9/10
 - 40s - loss: 0.7120 - accuracy: 0.4882 - val_loss: 0.7151 - val_accuracy: 0.4215
Epoch 10/10
 - 41s - loss: 0.7105 - accuracy: 0.4755 - val_loss: 0.7285 - val_accuracy: 0.4215
