In [5]:
import pandas as pd 
import numpy as np 
from sklearn.utils import shuffle

df = pd.DataFrame()
colnames=['Review','Sentiment'] 
df = pd.read_csv('combined_reviews.csv',encoding='utf-8',names=colnames)
df.set_index(['Review', 'Sentiment'])

df[df==np.inf]=np.nan
df.fillna(0, inplace=True)
df = shuffle(df).reset_index(drop=True)

X_train=df.loc[:550,'Review'].values
X_test=df.loc[551:,'Review'].values
Y_train=df.loc[:550,'Sentiment'].values
Y_test=df.loc[551:,'Sentiment'].values
df.head(10)

Review  Sentiment
0  రజినీకాంత్ నటిస్తోన్న కబాలి సినిమా విడుదల నెలక...          0
1  చిన్నతనం గ్యాంగ్స్టర్స్ చేయి తండ్రి కోల్పో సత్...          1
2  ఈ కెమెరా మీరు కోసం ఉత్తమ మరియు కొత్త 2017 మోడల...          1
3  హలో ఫ్రెండ్స్ ఈ వినోదం రంగం మరొక టెలివిజన్ సిస...          1
4  సగం అనే షార్ట్ నేమ్ కలుగు సతీష్ గణపతి ఆది తండ్...          1
5  నిజంగా ఈ ప్రోడక్ట్ అద్భుతం ఉండు ఈ ప్రోడక్ట్ యొ...          1
6  గౌతమ్ ( కళ్యాణ్ రామ్ ) తాను ఫ్యామిలీ అండ నిలువ...          0
7  LCD నిర్మాణం మీరు మొదట LCD నిర్మాణం తెలుసుకో అ...          0
8  నేను ఫోటో తియ్యి ఇప్పుడు ఈ కెమెరా ఉపయోగించు నే...          1
9  రెడ్మీ 4 A ఆ ధర విభాగం అత్యుత్తమ కిల్లర్ ఫోన్ ...          1

In [6]:
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences

tokenizer_obj = Tokenizer()
Total_Reviews = df.loc[:,'Review'].values
tokenizer_obj.fit_on_texts(Total_Reviews)

#pad sequence
max_length= max([len(s.split()) for s in Total_Reviews])

#size of the vocabulary
vocabulary_size = len(tokenizer_obj.word_index) +1 

X_train_tokens = tokenizer_obj.texts_to_sequences(X_train)
X_test_tokens = tokenizer_obj.texts_to_sequences(X_test)

X_train_pad = pad_sequences (X_train_tokens,maxlen=max_length,padding="post")
X_train_pad = np.nan_to_num(X_train_pad)

X_test_pad = pad_sequences (X_test_tokens,maxlen=max_length,padding="post")
X_test_pad = np.nan_to_num(X_test_pad)

Total_Reviews_tokens = tokenizer_obj.texts_to_sequences(Total_Reviews)
Total_reviews_pad = pad_sequences(Total_Reviews_tokens,maxlen=max_length,padding="post")

print(X_train_pad,X_test_pad)

[[1628 8946 1100 ...    0    0    0]
 [1936 8976  424 ...    0    0    0]
 [   4   69   87 ...    0    0    0]
 ...
 [ 521 2624 3706 ...    0    0    0]
 [1037  369   16 ...    0    0    0]
 [1805   27  944 ...    0    0    0]] [[  530   196   382 ...     0     0     0]
 [   28   162    42 ...     0     0     0]
 [ 6827  2314  1764 ...     0     0     0]
 ...
 [   94   832  2904 ...     0     0     0]
 [ 1996  1640   515 ...     0     0     0]
 [ 1081    56 22930 ...     0     0     0]]


In [ ]:
# Import svmmodel
from sklearn import svm
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(Total_reviews_pad,df.loc[:,'Sentiment'].values, test_size=0.2, random_state=42)
#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


672
672
